version: '3.4'

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf/fluentd.conf:/fluentd/etc/fluent.conf
      - ./log:/fluentd/rails_log
    ports:
      - 24224:24224

  elasticsearch:
    image: elasticsearch:6.6.0
    # volumes:
    #   - ./elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
    depends_on:
        - fluentd
    ports:
      - 9200:9200

  kibana:
    image: kibana:6.6.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
